## To encourage contributors to use issue templates, we don't allow blank issues
## it's valid schema
blank_issues_enabled: false

contact_links:
  - name: "\u2049 FAQ"
    url: 'https://github.com/#/faq'
    about: 'Make sure you have read the Frequently Asked Questions page.'
  - name: "\u2753 Slack Community"
    url: 'https://github.com/#/faq'
    about: 'Please ask support questions or discuss suggestions/enhancements here.'
